"""empty message

Revision ID: ad3b46269116
Revises: 
Create Date: 2019-08-19 09:02:12.648681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3b46269116'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('town', sa.VARCHAR(length=256), nullable=True),
    sa.Column('street', sa.VARCHAR(length=256), nullable=True),
    sa.Column('building', sa.VARCHAR(length=256), nullable=True),
    sa.Column('apartment', sa.Integer(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=8), nullable=True),
    sa.Column('relatives', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('import_id', 'citizen_id')
    )
    op.create_index(op.f('ix_data_birth_date'), 'data', ['birth_date'], unique=False)
    op.create_index(op.f('ix_data_citizen_id'), 'data', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_data_import_id'), 'data', ['import_id'], unique=False)
    op.create_index(op.f('ix_data_town'), 'data', ['town'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_town'), table_name='data')
    op.drop_index(op.f('ix_data_import_id'), table_name='data')
    op.drop_index(op.f('ix_data_citizen_id'), table_name='data')
    op.drop_index(op.f('ix_data_birth_date'), table_name='data')
    op.drop_table('data')
    # ### end Alembic commands ###
